const DEPARTMENTS = [
  { code: '05', name: 'Antioquia' },
  { code: '08', name: 'Atlántico' },
  { code: '11', name: 'Bogotá D.C.' },
  { code: '13', name: 'Bolívar' },
  { code: '15', name: 'Boyacá' },
  { code: '17', name: 'Caldas' },
  { code: '18', name: 'Caquetá' },
  { code: '19', name: 'Cauca' },
  { code: '20', name: 'Cesar' },
  { code: '23', name: 'Córdoba' },
  { code: '25', name: 'Cundinamarca' },
  { code: '27', name: 'Chocó' },
  { code: '41', name: 'Huila' },
  { code: '44', name: 'La Guajira' },
  { code: '47', name: 'Magdalena' },
  { code: '50', name: 'Meta' },
  { code: '52', name: 'Nariño' },
  { code: '54', name: 'Norte de Santander' },
  { code: '63', name: 'Quindío' },
  { code: '66', name: 'Risaralda' },
  { code: '68', name: 'Santander' },
  { code: '70', name: 'Sucre' },
  { code: '73', name: 'Tolima' },
  { code: '76', name: 'Valle del Cauca' },
  { code: '81', name: 'Arauca' },
  { code: '85', name: 'Casanare' },
  { code: '86', name: 'Putumayo' },
  { code: '88', name: 'San Andrés' },
  { code: '91', name: 'Amazonas' },
  { code: '94', name: 'Guainía' },
  { code: '95', name: 'Guaviare' },
  { code: '97', name: 'Vaupés' },
  { code: '99', name: 'Vichada' },
];

const MUNICIPALITIES = {
  '76': [
    { code: '76001', name: 'Cali' },
    { code: '76020', name: 'Alcalá' },
    { code: '76036', name: 'Andalucía' },
    { code: '76041', name: 'Ansermanuevo' },
    { code: '76054', name: 'Argelia' },
    { code: '76070', name: 'Bolívar' },
    { code: '76079', name: 'Buenaventura' },
    { code: '76089', name: 'Buga' },
    { code: '76100', name: 'Bugalagrande' },
    { code: '76109', name: 'Palmira' },
    { code: '76110', name: 'Caicedonia' },
    { code: '76122', name: 'Cartago' },
    { code: '76126', name: 'El Águila' },
    { code: '76130', name: 'El Cairo' },
    { code: '76133', name: 'El Cerrito' },
    { code: '76135', name: 'El Dovio' },
    { code: '76140', name: 'Florida' },
    { code: '76147', name: 'Ginebra' },
    { code: '76155', name: 'Guacarí' },
    { code: '76164', name: 'Jamundí' },
    { code: '76173', name: 'La Cumbre' },
    { code: '76174', name: 'La Unión' },
    { code: '76190', name: 'La Victoria' },
    { code: '76206', name: 'Obando' },
    { code: '76212', name: 'Pradera' },
    { code: '76227', name: 'Restrepo' },
    { code: '76233', name: 'Riofrío' },
    { code: '76244', name: 'Roldanillo' },
    { code: '76250', name: 'San Pedro' },
    { code: '76256', name: 'Sevilla' },
    { code: '76273', name: 'Tuluá' },
    { code: '76279', name: 'Toro' },
    { code: '76285', name: 'Trujillo' },
    { code: '76298', name: 'Ulloa' },
    { code: '76302', name: 'Versalles' },
    { code: '76318', name: 'Vijes' },
    { code: '76370', name: 'Yotoco' },
    { code: '76377', name: 'Yumbo' },
    { code: '76384', name: 'Zarzal' },
    { code: '76834', name: 'Dagua' },
    { code: '76845', name: 'Calima' },
    { code: '76855', name: 'Tenerife' },
  ],
};
const VOTING_STATIONS = {
  '76001': [
    { code: '7600101', name: 'UNIVERSIDAD DEL VALLE - SEDE MELÉNDEZ' },
    { code: '7600102', name: 'UNIVERSIDAD SANTIAGO DE CALI' },
    { code: '7600103', name: 'UNIVERSIDAD LIBRE - SEDE CALI' },
    { code: '7600104', name: 'UNIVERSIDAD ICESI' },
    { code: '7600105', name: 'UNIVERSIDAD PONTIFICIA BOLIVARIANA' },
    { code: '7600106', name: 'UNIVERSIDAD SAN BUENAVENTURA' },
    { code: '7600107', name: 'UNIVERSIDAD ANTONIO JOSÉ CAMACHO' },
    { code: '7600108', name: 'INSTITUCIÓN UNIVERSITARIA ANTONIO JOSÉ CAMACHO' },
    { code: '7600109', name: 'COLEGIO HELVETIA' },
    { code: '7600110', name: 'COLEGIO BOLÍVAR' },
    { code: '7600111', name: 'COLEGIO BERCHMANS' },
    { code: '7600112', name: 'COLEGIO NUESTRA SEÑORA DEL ROSARIO' },
    { code: '7600113', name: 'COLEGIO JORGE ISAACS' },
    { code: '7600114', name: 'COLEGIO SAN LUIS GONZAGA' },
    { code: '7600115', name: 'IE SANTA LIBRADA' },
    { code: '7600116', name: 'IE NORMAL SUPERIOR SANTIAGO DE CALI' },
    { code: '7600117', name: 'IE REPUBLICA DE COLOMBIA' },
    { code: '7600118', name: 'IE REPUBLICA DE ISRAEL' },
    { code: '7600119', name: 'IE REPUBLICA DEL ECUADOR' },
    { code: '7600120', name: 'IE GERMAN ARCINIEGAS' },
    { code: '7600121', name: 'IE JAVIERA ÁNGULO' },
    { code: '7600122', name: 'IE FERMIN TANGÜIS' },
    { code: '7600123', name: 'IE LICEO DEPARTAMENTAL' },
    { code: '7600124', name: 'IE CIUDAD DE CALI' },
    { code: '7600125', name: 'IE NUESTRA SEÑORA DE LA CANDELARIA' },
    { code: '7600126', name: 'IE CAMILO TORRES' },
    { code: '7600127', name: 'IE INEM JORGE ISAACS' },
    { code: '7600128', name: 'IE MARIA INMACULADA' },
    { code: '7600129', name: 'IE SAN JOSÉ MARLOG' },
    { code: '7600130', name: 'IE MARCO FIDEL SUÁREZ' },
    { code: '7600131', name: 'IE JOSÉ MARÍA CARBONELL' },
    { code: '7600132', name: 'IE MIGUEL ANTONIO ZAMBRANO' },
    { code: '7600133', name: 'IE HERNANDO CORTES' },
    { code: '7600134', name: 'IE GABRIELA MISTRAL' },
    { code: '7600135', name: 'IE HORACIO MATOSO' },
    { code: '7600136', name: 'IE SAN LUIS BELTRÁN' },
    { code: '7600137', name: 'IE ALFONSO LÓPEZ PUMAREJO' },
    { code: '7600138', name: 'IE CARLOS HOLMES TRUJILLO' },
    { code: '7600139', name: 'IE ANTONIO JOSÉ CAMACHO' },
    { code: '7600140', name: 'IE SANTA TERESITA' },
    { code: '7600141', name: 'IE REPUBLICA DE PANAMÁ' },
    { code: '7600142', name: 'IE TÉCNICO PROFESIONAL COMERCIO Y SERVICIOS' },
    { code: '7600143', name: 'IE AURELIO AMU GUERRERO' },
    { code: '7600144', name: 'IE CARLOS SARDI' },
    { code: '7600145', name: 'CENTRO COMERCIAL CHIPICHAPE' },
    { code: '7600146', name: 'CENTRO COMERCIAL UNICENTRO' },
    { code: '7600147', name: 'CENTRO COMERCIAL TERRAPLÉN' },
    { code: '7600148', name: 'CENTRO COMERCIAL COSMOCENTRO' },
    { code: '7600149', name: 'CENTRO COMERCIAL PASOANCHO' },
    { code: '7600150', name: 'CENTRO COMERCIAL 14 DE CALIMA' },
    { code: '7600151', name: 'CENTRO COMERCIAL LA PASARELA' },
    { code: '7600152', name: 'CENTRO COMERCIAL CENTENARIO' },
    { code: '7600153', name: 'CENTRO COMERCIAL PALMERA' },
    { code: '7600154', name: 'CENTRO COMERCIAL MAYORCA' },
    { code: '7600155', name: 'CENTRO COMERCIAL LA VICTORIA' },
    { code: '7600156', name: 'CASA DE LA CULTURA' },
    { code: '7600157', name: 'TEATRO MUNICIPAL' },
    { code: '7600158', name: 'BIBLIOTECA MUNICIPAL' },
    { code: '7600159', name: 'CENTRO CULTURAL COMFANDI' },
    { code: '7600160', name: 'SENA - CENTRO DE COMERCIO Y SERVICIOS' },
    { code: '7600161', name: 'SENA - CENTRO INDUSTRIAL Y DE AVIACIÓN' },
    { code: '7600162', name: 'SENA - CENTRO DE TELEINFORMÁTICA Y PRODUCCIÓN INDUSTRIAL' },
    { code: '7600163', name: 'SENA - CENTRO DE DISEÑO Y MANUFACTURA DEL CUERO' },
    { code: '7600164', name: 'IE ANTONIO HOLGUÍN GARCES' },
    { code: '7600165', name: 'IE CIUDAD DE PASTO' },
    { code: '7600166', name: 'IE GABRIEL GARCÍA MÁRQUEZ' },
    { code: '7600167', name: 'IE MONSEÑOR MANUEL GERMÁN CUELLIO' },
    { code: '7600168', name: 'IE NUESTRA SEÑORA DE LA MERCED' },
    { code: '7600169', name: 'IE REPUBLICA DE ARGENTINA' },
    { code: '7600170', name: 'IE REPUBLICA DE MÉXICO' },
    { code: '7600171', name: 'IE SAN PEDRO CLAVER' },
    { code: '7600172', name: 'IE SANTA ISABEL DE HUNGRÍA' },
    { code: '7600173', name: 'IE FRANCISCO DE PAULA SANTANDER' },
    { code: '7600174', name: 'IE LUIS CARLOS GALÁN SARMIENTO' },
    { code: '7600175', name: 'IE NUESTRA SEÑORA DEL PALMAR' },
  ],
};
const BARRIOS_CALI = [
  // Comuna 1
  { name: 'Siberia', comuna: 1 },
  { name: 'Villa del Lili', comuna: 1 },
  { name: 'Ciudad Jardín', comuna: 1 },
  { name: 'Colseguros', comuna: 1 },
  { name: 'El Caney', comuna: 1 },
  { name: 'La Hacienda', comuna: 1 },
  { name: 'Los Alcázares', comuna: 1 },
  { name: 'Mallorca', comuna: 1 },
  { name: 'Pance', comuna: 1 },
  { name: 'San Bosco', comuna: 1 },
  { name: 'San Fernando', comuna: 1 },
  { name: 'El Lago', comuna: 1 },
  // Comuna 2
  { name: 'Granada', comuna: 2 },
  { name: 'Los Cristales', comuna: 2 },
  { name: 'Los Robles', comuna: 2 },
  { name: 'Normandía', comuna: 2 },
  { name: 'San Pascual', comuna: 2 },
  { name: 'El Peñón', comuna: 2 },
  { name: 'Bosque Calderón', comuna: 2 },
  { name: 'La Merced', comuna: 2 },
  { name: 'Parcelaciones El Prado', comuna: 2 },
  { name: 'San Antonio', comuna: 2 },
  { name: 'Centro', comuna: 2 },
  { name: 'El Calvario', comuna: 2 },
  // Comuna 3
  { name: 'Santa Rita', comuna: 3 },
  { name: 'La Flora', comuna: 3 },
  { name: 'San Vicente', comuna: 3 },
  { name: 'Carlos Sardi', comuna: 3 },
  { name: 'Santa Teresita', comuna: 3 },
  { name: 'El Jardin', comuna: 3 },
  { name: 'El Troncal', comuna: 3 },
  { name: 'Santo Domingo', comuna: 3 },
  { name: 'El Bosque', comuna: 3 },
  { name: 'Quintas de Don Simón', comuna: 3 },
  // Comuna 4
  { name: 'Bella Vista', comuna: 4 },
  { name: 'Las Delicias', comuna: 4 },
  { name: 'La Unión', comuna: 4 },
  { name: 'El Retiro', comuna: 4 },
  { name: 'Sausalito', comuna: 4 },
  { name: 'Colina', comuna: 4 },
  { name: 'Altos del Vallado', comuna: 4 },
  { name: 'El Vallado', comuna: 4 },
  { name: 'Las Garzas', comuna: 4 },
  { name: 'Puente Tire', comuna: 4 },
  // Comuna 5
  { name: 'El Sena', comuna: 5 },
  { name: 'Galilea', comuna: 5 },
  { name: 'Illescas', comuna: 5 },
  { name: 'La Isla', comuna: 5 },
  { name: 'La Unión de Hazareto', comuna: 5 },
  { name: 'La Arcadia', comuna: 5 },
  { name: 'El Caney del Poblado', comuna: 5 },
  { name: 'Lomitas del Poblado', comuna: 5 },
  { name: 'Parcelas del Poblado', comuna: 5 },
  { name: 'Terranova', comuna: 5 },
  // Comuna 6
  { name: 'Cañaveralejo', comuna: 6 },
  { name: 'Las Acacias', comuna: 6 },
  { name: 'Los Naranjos', comuna: 6 },
  { name: 'San Fernando', comuna: 6 },
  { name: 'Las Gardenias', comuna: 6 },
  { name: 'Atanasio Girardot', comuna: 6 },
  { name: 'Brasil', comuna: 6 },
  { name: 'Flandes', comuna: 6 },
  { name: 'La Selva', comuna: 6 },
  { name: 'Venezuela', comuna: 6 },
  // Comuna 7
  { name: 'Las Granjas', comuna: 7 },
  { name: 'María Cano', comuna: 7 },
  { name: 'Ciudad Córdoba', comuna: 7 },
  { name: 'Séptimo de Agosto', comuna: 7 },
  { name: 'Los Laureles', comuna: 7 },
  { name: 'Los Pinos', comuna: 7 },
  { name: 'Santa Mónica', comuna: 7 },
  { name: 'Camichines', comuna: 7 },
  { name: 'El Laurel', comuna: 7 },
  { name: 'Rincón de Chile', comuna: 7 },
  // Comuna 8
  { name: 'Antonio Nariño', comuna: 8 },
  { name: 'Jorge Eliecer Gaitán', comuna: 8 },
  { name: 'La Esperanza', comuna: 8 },
  { name: 'Obrero', comuna: 8 },
  { name: 'San Cayetano', comuna: 8 },
  { name: 'El Crucero', comuna: 8 },
  { name: 'Villa España', comuna: 8 },
  { name: 'Los Amigos', comuna: 8 },
  { name: 'Rincón de los Artistas', comuna: 8 },
  { name: 'San Bernardino', comuna: 8 },
  // Comuna 9
  { name: 'Alfonso López', comuna: 9 },
  { name: 'Eduardo Santos', comuna: 9 },
  { name: 'La Fortaleza', comuna: 9 },
  { name: 'Pizarro', comuna: 9 },
  { name: 'San Luis', comuna: 9 },
  { name: 'San Nicolás', comuna: 9 },
  { name: 'Cementerio', comuna: 9 },
  { name: 'El Cortijo', comuna: 9 },
  { name: 'La Aurora', comuna: 9 },
  { name: 'Navarro', comuna: 9 },
  // Comuna 10
  { name: 'El Cortijo', comuna: 10 },
  { name: 'Carvajal', comuna: 10 },
  { name: 'La Primavera', comuna: 10 },
  { name: 'Los Buitrago', comuna: 10 },
  { name: 'Marroquín', comuna: 10 },
  { name: 'Morichal', comuna: 10 },
  { name: 'Paraíso', comuna: 10 },
  { name: 'Petecuy', comuna: 10 },
  { name: 'Santa Elena de los Andes', comuna: 10 },
  { name: 'Tingo', comuna: 10 },
  // Comuna 11
  { name: 'Belalcazar', comuna: 11 },
  { name: 'Bosque Capital', comuna: 11 },
  { name: 'Chiminangos', comuna: 11 },
  { name: 'Diamante', comuna: 11 },
  { name: 'El Diamante', comuna: 11 },
  { name: 'La Rivera', comuna: 11 },
  { name: 'Los Pajaritos', comuna: 11 },
  { name: 'Salomia', comuna: 11 },
  { name: 'Chipichape', comuna: 11 },
  { name: 'Los Cristales Sur', comuna: 11 },
  // Comuna 12
  { name: 'Eucarístico', comuna: 12 },
  { name: 'Guabal', comuna: 12 },
  { name: 'La Cupula', comuna: 12 },
  { name: 'Popular de los Andes', comuna: 12 },
  { name: 'San Martín de Loba', comuna: 12 },
  { name: 'Terraplén', comuna: 12 },
  { name: 'Bolivariano', comuna: 12 },
  { name: 'Villa del Carmen', comuna: 12 },
  { name: 'Jordán', comuna: 12 },
  { name: 'Isabel Pérez', comuna: 12 },
  // Comuna 13
  { name: 'El Ingenio', comuna: 13 },
  { name: 'Naranjal', comuna: 13 },
  { name: 'San Valentín', comuna: 13 },
  { name: 'El Refugio', comuna: 13 },
  { name: 'Marco Fidel Suárez', comuna: 13 },
  { name: 'Nuevo Chile', comuna: 13 },
  { name: 'Puente Grande', comuna: 13 },
  { name: 'Río Cali', comuna: 13 },
  { name: 'Villa del Rosario', comuna: 13 },
  { name: 'Versalles', comuna: 13 },
  // Comuna 14
  { name: 'Abisinia', comuna: 14 },
  { name: 'El荫ado', comuna: 14 },
  { name: 'María Auxiliadora', comuna: 14 },
  { name: 'Milan', comuna: 14 },
  { name: 'Santa Isabel', comuna: 14 },
  { name: 'Siete de Agosto', comuna: 14 },
  { name: 'El Carmelo', comuna: 14 },
  { name: 'La Silvania', comuna: 14 },
  { name: 'La Playa', comuna: 14 },
  { name: 'Valle del Lili', comuna: 14 },
  // Comuna 15
  { name: 'Alto Nápoles', comuna: 15 },
  { name: 'Altos de Menga', comuna: 15 },
  { name: 'Cementerio del Norte', comuna: 15 },
  { name: 'La Base', comuna: 15 },
  { name: 'La Independencia', comuna: 15 },
  { name: 'Las Palmas', comuna: 15 },
  { name: 'Menga', comuna: 15 },
  { name: 'Nápoles', comuna: 15 },
  { name: 'Santa Rosa de Cabal', comuna: 15 },
  { name: 'Voragine', comuna: 15 },
  // Comuna 16
  { name: 'Base Naval', comuna: 16 },
  { name: 'El Troncal del Mar', comuna: 16 },
  { name: 'La Paz', comuna: 16 },
  { name: 'Puerto Mallarino', comuna: 16 },
  { name: 'San Antonio del Río', comuna: 16 },
  { name: 'El Puerto', comuna: 16 },
  { name: 'Río Cauca', comuna: 16 },
  { name: 'Costa Mar', comuna: 16 },
  { name: 'El Porvenir', comuna: 16 },
  { name: 'El Poblado II', comuna: 16 },
  // Comuna 17
  { name: 'Barrio Nuevo', comuna: 17 },
  { name: 'El Cacique', comuna: 17 },
  { name: 'La Gaitana', comuna: 17 },
  { name: 'La Gloria', comuna: 17 },
  { name: 'Llano Verde', comuna: 17 },
  { name: 'Olimpico', comuna: 17 },
  { name: 'Tropical', comuna: 17 },
  { name: 'Villas de Sanabria', comuna: 17 },
  { name: 'San Pío', comuna: 17 },
  { name: 'La Frontera', comuna: 17 },
  // Comuna 18
  { name: 'Altos de Normandía', comuna: 18 },
  { name: 'Bellavista', comuna: 18 },
  { name: 'Cerro de los Cristales', comuna: 18 },
  { name: 'El Placer', comuna: 18 },
  { name: 'La Loma', comuna: 18 },
  { name: 'La Primavera de los Cristales', comuna: 18 },
  { name: 'Lourdes', comuna: 18 },
  { name: 'Natividad', comuna: 18 },
  { name: 'San Rafael', comuna: 18 },
  { name: 'Urbanización Evaristo Sourdis', comuna: 18 },
  // Comuna 19
  { name: 'Cedrolito', comuna: 19 },
  { name: 'Colmena', comuna: 19 },
  { name: 'Farallones', comuna: 19 },
  { name: 'La Sultana', comuna: 19 },
  { name: 'Las Ceibas', comuna: 19 },
  { name: 'Los Panches', comuna: 19 },
  { name: 'Montebello', comuna: 19 },
  { name: 'Pradera del Sur', comuna: 19 },
  { name: 'San Joaquín', comuna: 19 },
  { name: 'Villa Claudia', comuna: 19 },
  // Comuna 20
  { name: 'Altos de la Unión', comuna: 20 },
  { name: 'Brisas de los Andes', comuna: 20 },
  { name: 'El Horro', comuna: 20 },
  { name: 'El Tambo', comuna: 20 },
  { name: 'La Almería', comuna: 20 },
  { name: 'La Cascada', comuna: 20 },
  { name: 'La Morance', comuna: 20 },
  { name: 'La Sonrisa', comuna: 20 },
  { name: 'Los Andes', comuna: 20 },
  { name: 'Orquídeas', comuna: 20 },
  // Comuna 21
  { name: 'Comfandi Palmaseca', comuna: 21 },
  { name: 'El Jordán', comuna: 21 },
  { name: 'La Cumbre', comuna: 21 },
  { name: 'La Fortuna', comuna: 21 },
  { name: 'La Ribera', comuna: 21 },
  { name: 'Los Lagos', comuna: 21 },
  { name: 'Palmaseca', comuna: 21 },
  { name: 'Rancho Grande', comuna: 21 },
  { name: 'Santa Teresita del Baby', comuna: 21 },
  { name: 'Villa de los Alpes', comuna: 21 },
  // Comuna 22
  { name: 'Feliciano Cáceres', comuna: 22 },
  { name: 'Granja de la Esperanza', comuna: 22 },
  { name: 'La Pampa', comuna: 22 },
  { name: 'Las Malvinas', comuna: 22 },
  { name: 'Los Alpes', comuna: 22 },
  { name: 'Los Chorros', comuna: 22 },
  { name: 'Monterrey', comuna: 22 },
  { name: 'Portal de Comfandi', comuna: 22 },
  { name: 'Solelim', comuna: 22 },
  { name: 'Villa Esperanza', comuna: 22 },
];

function getDepartments() { return DEPARTMENTS; }
function getMunicipalities(deptCode) { return MUNICIPALITIES[deptCode] || []; }
function getVotingStations(munCode) { return VOTING_STATIONS[munCode] || []; }
function searchDepartments(q) {
  const lq = (q || '').toLowerCase();
  return DEPARTMENTS.filter(d => d.name.toLowerCase().includes(lq));
}
function searchMunicipalities(deptCode, q) {
  const muns = MUNICIPALITIES[deptCode] || [];
  const lq = (q || '').toLowerCase();
  return muns.filter(m => m.name.toLowerCase().includes(lq));
}
function searchVotingStations(munCode, q) {
  const stations = VOTING_STATIONS[munCode] || [];
  const lq = (q || '').toLowerCase();
  return stations.filter(s => s.name.toLowerCase().includes(lq));
}
function getBarriosCali() { return BARRIOS_CALI; }
function searchBarriosCali(q) {
  const lq = (q || '').toLowerCase();
  return BARRIOS_CALI.filter(b => b.name.toLowerCase().includes(lq));
}
function getComunaByBarrio(name) {
  const found = BARRIOS_CALI.find(b => b.name === name);
  return found ? found.comuna : null;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    getDepartments, getMunicipalities, getVotingStations,
    searchDepartments, searchMunicipalities, searchVotingStations,
    getBarriosCali, searchBarriosCali, getComunaByBarrio,
  };
}
